name: orix_food_delivery
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3

  carousel_slider: ^2.0.0
  path_provider: ^1.6.9
  shared_preferences: '>=0.5.0 <2.0.0'
  email_validator: ^1.0.0
  font_awesome_flutter: ^8.8.1
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.6
  fluttertoast: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - resources/images/

  fonts:
    - family: Gilroy
      fonts:
        - asset: resources/fonts/Gilroy-Regular.ttf
    - family: Gilroy-Bold
      fonts:
        - asset: resources/fonts/Gilroy-Bold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
